### ISSUE TITLE
Status for unjustified emendations

### ISSUE THREAD

**Issue by mdoering** [SpeciesFileGroup/nomen#22]
Which NOMEN status would best reflect the status of a name published as an `unjustified emendations` (Art. 33.2.3)?

> An unjustified emendation is to be seen as a separate proposal: a name proposed in its own right with authorship + date from the publication where it is first proposed (but for practical reasons it should be tagged as “unjustified emendation”). An unjustified emendation has no effects on the older name that is being (unjustifiably) emended, but the unjustified emendation is still connected to that older name as a homotypic synonym.

**Comment by proceps** [comment]
ICZN unjustified mendation
http://purl.obolibrary.org/obo/NOMEN_0000278

**Comment by proceps** [comment]
a subclass of objective synonym (homotypic synonym is a botanical term)

**Comment by mjy** [comment]
@proceps that's a relationship, as it should be because it's an assertion b/w 2 names.

I think what @mdoering likely wants is the corresponding Classification that is inferred on the domain of that property.  I'm pretty sure we don't have that class.

If we add it, then we need to be able to assert that that Classification should never be chosen in TW, but only inferred by the relationship, as it only ever makes sense to assert that Classification in the context of 2 names (correct, emendation), not one.

**Comment by mdoering** [comment]
Interesting. I came here because of a similar problem with incorrect spellings which we require in COL so far to be relations:
https://github.com/CatalogueOfLife/backend/issues/908

Quite similar thinking

**Comment by mjy** [comment]
Exactly, a misspelling (and many other things), can never be known without reference to 2 names.  In fact most assertions are like this.

In TW the only time we use Classifications (assertions on one name) is when we have to assert that some inferred status is over-ridden by so-and-so who is treating the name as in/valid.
